## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per environment.
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: true
  group_base: ou=retirement,dc=retirement,dc=unal,dc=edu,dc=co
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  
## Environment

development:
  host: 104.196.22.25
  port: 389
  attribute: cn
  base: "ou=retirement,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_user: "cn=admin,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_password: "admin"
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  host: 104.196.22.25
  port: 389
  attribute: cn
  base: "ou=retirement,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_user: "cn=admin,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_password: "admin"
  ssl: false
  # <<: *AUTHORIZATIONS


production:
  host: 104.196.22.25
  port: 389
  attribute: cn
  base: "ou=retirement,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_user: "cn=admin,dc=retirement,dc=unal,dc=edu,dc=co"
  admin_password: "admin"
  ssl: false
  # <<: *AUTHORIZATIONS

